const customerData = {
    reg_no: "",
    id_type: "",
    id_no: "",
    first_name: "",
    middle_name: "",
    last_name: "",
    phone_no: "",
    dob: "",
    blood_type: "",
    nationality: "",
    gender: "",
    region: "",
    city: "",
    subcity: "",
    woreda: "",
    house_no: "",
    marriage_status: "",
    marriage_id: "",
    emerg_contact_name: "",
    emerg_contact_phone: "",
    customer_type: "",
}

export default customerData;